# NovaPay Technical Documentation - body PDF generator (ReportLab)
import hashlib
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.enums import TA_LEFT, TA_CENTER
from reportlab.lib import colors
from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer, PageBreak,
                                Table, TableStyle, CondPageBreak, HRFlowable)
from reportlab.platypus.tableofcontents import TableOfContents
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.pdfmetrics import registerFontFamily

# ---- Fonts (host-available, Times-metric-compatible) ----
pdfmetrics.registerFont(TTFont('Times New Roman', '/usr/share/fonts/truetype/liberation/LiberationSerif-Regular.ttf'))
pdfmetrics.registerFont(TTFont('Times New Roman Bold', '/usr/share/fonts/truetype/liberation/LiberationSerif-Bold.ttf'))
pdfmetrics.registerFont(TTFont('Calibri', '/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf'))
pdfmetrics.registerFont(TTFont('Calibri Bold', '/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf'))
pdfmetrics.registerFont(TTFont('DejaVuSans', '/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf'))
registerFontFamily('Times New Roman', normal='Times New Roman', bold='Times New Roman Bold', italic='Times New Roman', boldItalic='Times New Roman Bold')
registerFontFamily('Calibri', normal='Calibri', bold='Calibri Bold', italic='Calibri', boldItalic='Calibri Bold')
registerFontFamily('DejaVuSans', normal='DejaVuSans', bold='DejaVuSans')

# ---- Palette (auto-generated by pdf.py palette.cascade) ----
PAGE_BG       = colors.HexColor('#f0f1f1')
CARD_BG       = colors.HexColor('#e8ebed')
TABLE_STRIPE  = colors.HexColor('#ecedee')
HEADER_FILL   = colors.HexColor('#486c7e')
BORDER        = colors.HexColor('#adbcc3')
ACCENT        = colors.HexColor('#c82d47')
TEXT_PRIMARY  = colors.HexColor('#1c1e1f')
TEXT_MUTED    = colors.HexColor('#72797c')
SEM_INFO      = colors.HexColor('#4e759c')

TABLE_HEADER_COLOR = HEADER_FILL
TABLE_ROW_EVEN = colors.white
TABLE_ROW_ODD = TABLE_STRIPE

# ---- Page geometry ----
MARGIN = 2.0 * cm
PAGE_W, PAGE_H = A4
AVAIL_W = PAGE_W - 2 * MARGIN
available_height = PAGE_H - 2 * MARGIN
H1_ORPHAN = available_height * 0.15

# ---- Styles ----
FN = 'Times New Roman'
h1 = ParagraphStyle('H1', fontName=FN, fontSize=20, leading=26, spaceBefore=18,
                    spaceAfter=10, textColor=TEXT_PRIMARY)
h2 = ParagraphStyle('H2', fontName=FN, fontSize=14, leading=20, spaceBefore=14,
                    spaceAfter=6, textColor=TEXT_PRIMARY)
h3 = ParagraphStyle('H3', fontName=FN, fontSize=11.5, leading=16, spaceBefore=10,
                    spaceAfter=4, textColor=TEXT_PRIMARY)
body = ParagraphStyle('Body', fontName=FN, fontSize=10.5, leading=16,
                      alignment=TA_LEFT, spaceAfter=8, textColor=TEXT_PRIMARY)
bullet = ParagraphStyle('Bullet', parent=body, leftIndent=14, bulletIndent=2, spaceAfter=3)
caption = ParagraphStyle('Caption', fontName=FN, fontSize=8.5, leading=12,
                         alignment=TA_CENTER, textColor=TEXT_MUTED, spaceBefore=3, spaceAfter=6)
code_style = ParagraphStyle('Code', fontName='DejaVuSans', fontSize=8, leading=11,
                            textColor=TEXT_PRIMARY, backColor=CARD_BG, borderPadding=4,
                            leftIndent=6, spaceBefore=4, spaceAfter=8)
th = ParagraphStyle('TH', fontName=FN, fontSize=9, leading=12, textColor=colors.white, alignment=TA_LEFT)
td = ParagraphStyle('TD', fontName=FN, fontSize=9, leading=12, textColor=TEXT_PRIMARY, alignment=TA_LEFT)
tdm = ParagraphStyle('TDm', parent=td, fontName='DejaVuSans', fontSize=7.5, leading=10)

# ---- TOC machinery ----
class TocDocTemplate(SimpleDocTemplate):
    def afterFlowable(self, flowable):
        if hasattr(flowable, 'bookmark_name'):
            self.notify('TOCEntry', (getattr(flowable, 'bookmark_level', 0),
                                     getattr(flowable, 'bookmark_text', ''),
                                     self.page,
                                     getattr(flowable, 'bookmark_key', '')))

def heading(text, style, level=0):
    key = 'h_%s' % hashlib.md5(text.encode()).hexdigest()[:8]
    p = Paragraph('<a name="%s"/><b>%s</b>' % (key, text), style)
    p.bookmark_name = text
    p.bookmark_level = level
    p.bookmark_text = text
    p.bookmark_key = key
    return p

def h1_block(text):
    return [CondPageBreak(H1_ORPHAN),
            heading(text, h1, 0),
            HRFlowable(width='100%', thickness=1.2, color=HEADER_FILL, spaceAfter=8)]

def h2_block(text):
    return [CondPageBreak(60), heading(text, h2, 1)]

story = []

# ================= TOC =================
toc = TableOfContents()
toc.levelStyles = [
    ParagraphStyle('TOC1', fontName=FN, fontSize=10.5, leading=14.5, leftIndent=6),
    ParagraphStyle('TOC2', fontName=FN, fontSize=9, leading=12.5, leftIndent=24, textColor=TEXT_MUTED),
]
story.append(Paragraph('<b>Table of Contents</b>', ParagraphStyle('TocTitle', parent=h1, spaceBefore=0)))
story.append(HRFlowable(width='100%', thickness=1.2, color=HEADER_FILL, spaceAfter=12))
story.append(toc)
story.append(PageBreak())

# ================= 1. Executive Overview =================
story.extend(h1_block('1. Executive Overview'))
story.append(Paragraph(
    'NovaPay is a cross-border banking product for users in Nigeria who want to hold, move and grow '
    'money in multiple currencies. The platform combines an NGN home rail (funding via Nigerian payment '
    'gateways and payouts to Nigerian banks and mobile money) with USD and EUR wallets, virtual foreign '
    'accounts for receiving international transfers, virtual (and physical) USD cards, transparent '
    'foreign-exchange conversion, stablecoin custody, and business accounts with approval-gated bulk payouts. '
    'It is delivered as a monorepo with three applications:', body))
story.append(Paragraph('• <b>apps/api</b> - a NestJS 11 modular-monolith REST API backed by PostgreSQL '
                       '(Supabase) and Redis, using Drizzle ORM and a double-entry ledger.', bullet))
story.append(Paragraph('• <b>apps/mobile</b> - the customer app, built with Expo (React Native) and '
                       'expo-router, covering onboarding, wallets, cards, conversions, bills and business features.', bullet))
story.append(Paragraph('• <b>apps/admin</b> - an operations console (React 19 + Vite) for KYC review, '
                       'customer management, transaction inspection, support tickets, AML alerts, disputes and reconciliation.', bullet))
story.append(Spacer(1, 6))
story.append(Paragraph(
    'Development followed a phased roadmap (Phase 0 through Phase 8 for the backend, F0 through F7 for the '
    'mobile frontend), each phase documented under <font name="DejaVuSans">docs/</font>. All backend phases and '
    'all frontend phases are marked complete in their phase documents; partner integrations (Flutterwave, '
    'KYC/BaaS/card issuers) are currently wired to mock providers that can be swapped for production providers '
    'via environment configuration.', body))

kv = [
    ('Product', 'NovaPay cross-border banking (NGN / USD / EUR + USDC / USDT)'),
    ('Backend', 'NestJS 11, TypeScript 5.7, Drizzle ORM, PostgreSQL (Supabase), Redis 7'),
    ('Mobile', 'Expo 54 / React Native 0.81, expo-router 6, React 19'),
    ('Admin', 'React 19 + Vite 6 + React Router 7'),
    ('Auth', 'Phone-OTP passwordless, JWT access/refresh with rotation, API keys, step-up'),
    ('Ledger', 'Double-entry, minor units (kobo/cents), idempotent transaction creation'),
    ('Deployment', 'Docker Compose (Redis + optional Postgres), multi-stage Node 22 image, GitHub Actions CI'),
]
t = Table([[Paragraph('<b>%s</b>' % k, td), Paragraph(v, td)] for k, v in kv],
          colWidths=[0.22 * AVAIL_W, 0.78 * AVAIL_W], hAlign='CENTER')
t.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (0, -1), CARD_BG),
    ('GRID', (0, 0), (-1, -1), 0.5, BORDER),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('LEFTPADDING', (0, 0), (-1, -1), 8), ('RIGHTPADDING', (0, 0), (-1, -1), 8),
    ('TOPPADDING', (0, 0), (-1, -1), 5), ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
]))
story.append(t)
story.append(Paragraph('Table 1 - Platform summary', caption))

# ================= 2. System Architecture =================
story.extend(h1_block('2. System Architecture'))
story.extend(h2_block('2.1 Repository Layout and Infrastructure'))
story.append(Paragraph(
    'The repository is an npm monorepo without a root workspace; each application under '
    '<font name="DejaVuSans">apps/</font> has its own package.json, lockfile and scripts. Infrastructure is '
    'defined in <font name="DejaVuSans">docker-compose.yml</font>, which runs Redis 7 (port 6379, AOF '
    'persistence, healthcheck) and an optional PostgreSQL 16 (port 5432, activated with the '
    '<font name="DejaVuSans">local-db</font> profile). In practice PostgreSQL is hosted on Supabase: the '
    'runtime connection uses the Supabase connection pooler (port 6543) while Drizzle migrations use the '
    'direct connection (port 5432).', body))
story.append(Paragraph(
    'The API ships as a three-stage <font name="DejaVuSans">node:22-alpine</font> Dockerfile (deps, build+prune, '
    'runner as non-root node user) exposing port 3000. GitHub Actions CI runs on pushes and PRs to main/develop: '
    'it installs dependencies, lints, runs Jest unit tests (with a Redis service container) and builds the API '
    'on Node 22.', body))
story.extend(h2_block('2.2 Technology Stack'))
def tech_table(rows, title):
    data = [[Paragraph('<b>%s</b>' % c, th) for c in rows[0]]]
    for r in rows[1:]:
        data.append([Paragraph(c, tdm if i == 0 else td) for i, c in enumerate(r)])
    tt = Table(data, colWidths=[w * AVAIL_W for w in [0.32, 0.30, 0.38]], hAlign='CENTER', repeatRows=1)
    style = [('BACKGROUND', (0, 0), (-1, 0), TABLE_HEADER_COLOR),
             ('GRID', (0, 0), (-1, -1), 0.5, BORDER),
             ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
             ('LEFTPADDING', (0, 0), (-1, -1), 6), ('RIGHTPADDING', (0, 0), (-1, -1), 6),
             ('TOPPADDING', (0, 0), (-1, -1), 4), ('BOTTOMPADDING', (0, 0), (-1, -1), 4)]
    for i in range(1, len(data)):
        style.append(('BACKGROUND', (0, i), (-1, i), TABLE_ROW_ODD if i % 2 else TABLE_ROW_EVEN))
    tt.setStyle(TableStyle(style))
    story.append(Spacer(1, 6)); story.append(tt); story.append(Paragraph(title, caption))

tech_table([
    ('Layer', 'Technology', 'Role'),
    ('apps/api', 'NestJS 11 / TypeScript 5.7', 'REST API, modular monolith'),
    ('Data', 'Drizzle ORM 0.45 + PostgreSQL (Supabase)', 'Schema, migrations, queries'),
    ('Cache/State', 'Redis 7 (ioredis)', 'OTP, refresh tokens, idempotency, rate limits, FX cache'),
    ('Mobile', 'Expo 54 / RN 0.81 / expo-router 6', 'Customer app (iOS/Android)'),
    ('Admin', 'React 19 + Vite 6 + Router 7', 'Operations console'),
    ('Validation', 'Zod 4 (env) + class-validator (DTOs)', 'Config and request validation'),
    ('Observability', 'nestjs-pino, @nestjs/terminus, Swagger 11', 'Logging, health checks, API docs'),
    ('Security', 'helmet, @nestjs/throttler 6, passport-jwt', 'Headers, rate limiting, auth'),
    ('Tests', 'Jest 30 + supertest', 'Unit and e2e tests'),
    ('CI/CD', 'GitHub Actions', 'Lint, test, build'),
], 'Table 2 - Technology stack')

story.extend(h2_block('2.3 Request Pipeline'))
story.append(Paragraph(
    'Every request flows through the following globally-registered layers, configured in '
    '<font name="DejaVuSans">src/main.ts</font> and <font name="DejaVuSans">src/app.module.ts</font>:', body))
story.append(Paragraph('• <b>helmet</b> security headers and a 1 MB JSON body limit.', bullet))
story.append(Paragraph('• <b>ThrottlerGuard</b> - global rate limiting, with a tighter dedicated limit on OTP endpoints.', bullet))
story.append(Paragraph('• <b>JwtAuthGuard</b> - global authentication accepting JWTs (access tokens) or API keys '
                       '(<font name="DejaVuSans">np_test_...</font> / <font name="DejaVuSans">np_live_...</font>); routes marked '
                       '<font name="DejaVuSans">@Public()</font> are exempt.', bullet))
story.append(Paragraph('• <b>IdempotencyInterceptor</b> - for POST requests carrying an '
                       '<font name="DejaVuSans">Idempotency-Key</font> header, a Redis lock plus a 24-hour cached '
                       'response makes retries safe.', bullet))
story.append(Paragraph('• <b>GlobalExceptionFilter</b> - converts all errors into a uniform envelope '
                       '<font name="DejaVuSans">{ success, message, error: { code, message, details } }</font> using a '
                       'central error-code catalogue.', bullet))
story.append(Paragraph('• <b>ValidationPipe</b> - whitelist-based DTO validation on every route.', bullet))
story.append(Paragraph(
    'Health endpoints (<font name="DejaVuSans">GET /health</font> checks both PostgreSQL and Redis; '
    '<font name="DejaVuSans">GET /health/live</font> is a liveness probe) are provided via Terminus. Swagger '
    'documentation is served at <font name="DejaVuSans">/docs</font> when '
    '<font name="DejaVuSans">SWAGGER_ENABLED</font> is set.', body))

# ================= 3. Backend API =================
story.extend(h1_block('3. Backend API Reference'))
story.append(Paragraph(
    'The API is organised into NestJS modules under <font name="DejaVuSans">apps/api/src/modules/</font>. All '
    'routes are versioned under <font name="DejaVuSans">/v1</font>. Amounts are integers in minor units '
    '(kobo for NGN, cents for USD/EUR). The tables below list the principal endpoints per module.', body))

def ep_table(rows, title):
    data = [[Paragraph('<b>Endpoint</b>', th), Paragraph('<b>Description</b>', th)]]
    for r in rows:
        data.append([Paragraph(r[0], tdm), Paragraph(r[1], td)])
    tt = Table(data, colWidths=[0.46 * AVAIL_W, 0.54 * AVAIL_W], hAlign='CENTER', repeatRows=1)
    style = [('BACKGROUND', (0, 0), (-1, 0), TABLE_HEADER_COLOR),
             ('GRID', (0, 0), (-1, -1), 0.5, BORDER),
             ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
             ('LEFTPADDING', (0, 0), (-1, -1), 6), ('RIGHTPADDING', (0, 0), (-1, -1), 6),
             ('TOPPADDING', (0, 0), (-1, -1), 4), ('BOTTOMPADDING', (0, 0), (-1, -1), 4)]
    for i in range(1, len(data)):
        style.append(('BACKGROUND', (0, i), (-1, i), TABLE_ROW_ODD if i % 2 else TABLE_ROW_EVEN))
    tt.setStyle(TableStyle(style))
    story.append(Spacer(1, 6)); story.append(tt); story.append(Paragraph(title, caption))

story.extend(h2_block('3.1 Authentication and Sessions'))
story.append(Paragraph(
    'Authentication is passwordless. A user requests an OTP for their phone number; the code is stored in Redis '
    'as a salted SHA-256 hash (pepper + phone + code) with a 300-second TTL and timing-safe comparison. Attempt '
    'counters lock out abusive phones. On first successful verification a user record is created (with a unique '
    '@tag) and NGN, USD and EUR wallets are provisioned.', body))
story.append(Paragraph(
    'JWTs carry sub, phone, kycTier and platformRole claims. Refresh tokens are registered by jti in Redis and '
    'rotate on every refresh (the old jti is deleted first); logout revokes the pair and '
    '<font name="DejaVuSans">logout/all</font> revokes the entire jti set. High-value payouts above '
    '<font name="DejaVuSans">AUTH_STEPUP_PAYOUT_MINOR</font> require a recent step-up verification.', body))
ep_table([
    ('POST /v1/auth/otp/request', 'Send a login OTP to a phone number'),
    ('POST /v1/auth/otp/verify', 'Verify OTP; creates user + wallets on first login; returns token pair'),
    ('POST /v1/auth/token/refresh', 'Rotate refresh token and issue a new access token'),
    ('POST /v1/auth/logout, /v1/auth/logout/all', 'Revoke current refresh token / all sessions'),
    ('POST /v1/auth/step-up/request, /verify', 'Step-up verification for sensitive operations'),
    ('GET /v1/auth/me, PATCH /v1/auth/profile', 'Read and update the authenticated profile'),
    ('POST /v1/auth/kyc', 'Submit KYC information'),
], 'Table 3 - Auth endpoints')
story.append(Paragraph(
    'SMS delivery for OTPs is pluggable: log, generic HTTP, Twilio and Infobip providers are selected by '
    '<font name="DejaVuSans">SMS_OTP_MODE</font>; the dev fixed code and the log provider are refused in '
    'production and staging environments.', body))

story.extend(h2_block('3.2 Wallets and Ledger'))
story.append(Paragraph(
    'The ledger is the system of record. Every money movement creates a transaction row and balanced '
    'double-entry <font name="DejaVuSans">ledger_entries</font> (debit/credit legs with running '
    '<font name="DejaVuSans">balanceAfter</font>). System wallets (including a dedicated '
    '<font name="DejaVuSans">fees</font> wallet) are keyed by <font name="DejaVuSans">SYSTEM_WALLET_KEYS</font>. '
    'Transaction creation is idempotent via a unique idempotency key. Wallet balances are derived as the sum of '
    'ledger entries.', body))
ep_table([
    ('GET /v1/wallets', 'List the caller\'s wallets with balances'),
    ('GET /v1/transactions', 'Paginated transaction history'),
    ('GET /v1/transactions/:id', 'Single transaction detail'),
], 'Table 4 - Wallet and transaction endpoints')

story.extend(h2_block('3.3 Payments: Funding and Payouts'))
story.append(Paragraph(
    'Payment rails implement a <font name="DejaVuSans">PaymentRailProvider</font> interface with two '
    'implementations: a mock rail (for development and tests) and a Flutterwave provider for the NGN rail, '
    'selected by <font name="DejaVuSans">PAYMENT_RAIL=auto|mock|flutterwave</font>. Funding credits the '
    'user\'s wallet after rail confirmation (webhook or simulation). Payouts run a full risk pipeline: KYC tier '
    'limits, sanctions screening, velocity checks, fee computation, step-up verification and ledger holds.', body))
ep_table([
    ('GET /v1/payments/rail', 'Which payment rail is active'),
    ('GET /v1/payments/banks/ng', 'Nigerian bank list for payouts'),
    ('POST /v1/payments/fund', 'Initiate a wallet funding (NGN rail)'),
    ('POST /v1/payments/fund/:id/simulate-complete', 'Simulate rail completion (mock/dev)'),
    ('POST /v1/payments/payout', 'Pay out to a bank account or mobile money'),
    ('POST /v1/payments/flutterwave/webhook', 'Signature-verified Flutterwave webhook'),
    ('GET /v1/payments/flutterwave/return', 'Redirect landing after hosted funding'),
    ('POST /v1/beneficiaries, GET /v1/beneficiaries', 'Manage payout beneficiaries (bank / mobile money)'),
], 'Table 5 - Payment endpoints')

story.extend(h2_block('3.4 Foreign Exchange'))
story.append(Paragraph(
    'FX quotes are transparent: the client rate is the mid-market rate (static, HTTP frankfurter, or auto mode, '
    'cached in Redis with a configurable TTL) minus a disclosed margin in basis points. A quote is locked for '
    '<font name="DejaVuSans">FX_QUOTE_TTL_SECONDS</font> and then booked via a double-entry conversion that is '
    'balanced per currency through system wallets. Rounding rules are covered by dedicated unit tests '
    '(<font name="DejaVuSans">fx.math.spec.ts</font>).', body))
ep_table([
    ('GET /v1/fx/rate', 'Current mid rate for a currency pair'),
    ('POST /v1/fx/quotes', 'Request a locked quote with margin applied'),
    ('POST /v1/fx/quotes/:id/book', 'Book an open quote; executes the conversion'),
], 'Table 6 - FX endpoints')

story.extend(h2_block('3.5 Cards (USD)'))
story.append(Paragraph(
    'Virtual USD cards are issued against a user\'s USD wallet via a mock card issuer '
    '(<font name="DejaVuSans">mock-card-issuer.ts</font>). Authorisations place a hold; settlement posts a '
    '<font name="DejaVuSans">card_spend</font> transaction. PANs are never stored - only brand and last4. '
    'Physical cards add shipping fields and a fulfilment status.', body))
ep_table([
    ('POST /v1/cards, GET /v1/cards', 'Create and list cards'),
    ('POST /v1/cards/authorizations/:authId/settle', 'Settle a card authorisation'),
    ('POST /v1/cards/:id/freeze | unfreeze | close', 'Card lifecycle controls'),
    ('POST /v1/cards/:id/authorize', 'Simulate a card authorisation (hold)'),
], 'Table 7 - Card endpoints')

story.extend(h2_block('3.6 Receiving: Virtual Accounts'))
story.append(Paragraph(
    'Users can be issued USD and EUR virtual accounts through a BaaS provider (mock in this build). Inbound '
    'credits - simulated or delivered by the BaaS webhook - land in the matching wallet and pass AML screening. '
    'One virtual account per user per currency is enforced.', body))
ep_table([
    ('POST /v1/accounts/virtual, GET /v1/accounts/virtual', 'Issue and list virtual accounts'),
    ('POST /v1/accounts/virtual/:id/simulate-inbound', 'Simulate an inbound international credit'),
    ('POST /v1/accounts/baas/webhook', 'Inbound credit webhook from the BaaS provider'),
], 'Table 8 - Virtual account endpoints')

story.extend(h2_block('3.7 Bills and Airtime'))
ep_table([
    ('GET /v1/bills/catalog, GET /v1/airtime/operators', 'Nigerian bill categories and airtime operators'),
    ('POST /v1/bills/pay, POST /v1/airtime/topup', 'Pay a bill / buy airtime (NGN debit)'),
], 'Table 9 - Bills endpoints')

story.extend(h2_block('3.8 Business Accounts and Bulk Payouts'))
story.append(Paragraph(
    'Organisations have owner/admin/approver/member roles with per-member '
    '<font name="DejaVuSans">approvalLimitMinor</font>. Bulk payout batches above an approver\'s limit must be '
    'approved before processing; each item becomes its own transaction with individual failure reasons.', body))
ep_table([
    ('POST/GET /v1/business/organizations', 'Create and list organisations'),
    ('POST/GET /v1/business/organizations/:orgId/members', 'Add and list org members'),
    ('GET .../wallet, POST .../wallet/fund', 'Org wallet balance and funding'),
    ('GET/POST .../bulk-payouts, POST .../bulk-payouts/:batchId/approve', 'Create, list and approve bulk payout batches'),
], 'Table 10 - Business endpoints')

story.extend(h2_block('3.9 Stablecoins, Developer API, Fees'))
ep_table([
    ('GET /v1/stablecoins, GET /v1/stablecoins/balances', 'Supported stablecoins and balances'),
    ('POST /v1/stablecoins/deposit, /v1/stablecoins/convert', 'Deposit USDC/USDT; convert to/from USD at 1:1 (sandbox custody)'),
    ('POST/GET /v1/developer/api-keys, POST .../:id/revoke', 'Programmatic API keys with scopes'),
    ('POST/GET /v1/developer/webhooks', 'Register webhook endpoints'),
    ('GET /v1/public/wallets, GET /v1/public/transactions', 'API-key-scoped read APIs'),
    ('GET /v1/fees/quote', 'Quote the fee for a transaction type and amount'),
], 'Table 11 - Stablecoin, developer and fee endpoints')

story.extend(h2_block('3.10 Support and Admin Operations'))
ep_table([
    ('POST/GET /v1/support/tickets, GET .../:id, POST .../:id/messages|reopen', 'Customer support tickets'),
    ('GET /v1/admin/kyc, POST /v1/admin/kyc/:id/review', 'KYC queue and approve/reject (sets tier_1/tier_2)'),
    ('GET /v1/admin/users, GET/PATCH /v1/admin/users/:id (status, role)', 'Customer management'),
    ('GET /v1/admin/transactions, GET .../:id', 'Platform-wide transactions with ledger legs'),
    ('GET/POST/PATCH /v1/admin/support/tickets', 'Support queue and ticket handling'),
    ('GET /v1/admin/compliance/alerts, PATCH .../:id', 'AML alert review (dismiss / confirm)'),
    ('POST /v1/admin/compliance/disputes/:id/resolve', 'Resolve disputes (won reverses the ledger)'),
    ('POST /v1/admin/compliance/retention/purge', 'NDPR data purge of closed users'),
    ('POST /v1/admin/reconciliation/run, GET .../report/:date', 'Flutterwave vs ledger reconciliation'),
], 'Table 12 - Support and admin endpoints')

# ================= 4. Database =================
story.extend(h1_block('4. Database Schema'))
story.append(Paragraph(
    'The schema (<font name="DejaVuSans">apps/api/src/database/schema.ts</font>, migrations in '
    '<font name="DejaVuSans">apps/api/drizzle/</font>) uses UUID primary keys, bigint minor-unit amounts and '
    'timestamptz columns throughout. Twenty-plus tables and enums model the domain; the core financial tables '
    'are described below.', body))
story.extend(h2_block('4.1 Core Tables'))
ep_table([
    ('users', 'phone (unique), email, tag (unique), status, kycTier (tier_0/1/2), platformRole (customer/support/admin)'),
    ('wallets', 'ownerType (user/system/organization), userId, systemKey, currency; unique per (owner, currency)'),
    ('transactions', 'type (fund, payout, convert, card_spend, receive, bill, airtime, bulk_payout, reversal, ...), '
                     'status, amount, fee, source/dest wallet, unique idempotencyKey, externalReference'),
    ('ledger_entries', 'walletId, transactionId, direction (debit/credit), amount, balanceAfter'),
    ('beneficiaries', 'type (bank / mobile_money), bank or MoMo details (mtn/airtel/mpesa/vodafone), currency, country'),
    ('cards', 'walletId, processorRef (unique), brand, last4 only, expiry, status, form (virtual/physical), spendLimitMinor, shipping'),
    ('virtual_accounts', 'walletId, currency, providerRef, accountNumber/iban/bic; unique (userId, currency)'),
    ('fx_quotes', 'pair, amounts, midRate, clientRate, marginBps, status (open/booked/expired), expiresAt, bookedTransactionId'),
    ('kyc_records', 'document type/number, verificationStatus, providerRef'),
    ('organizations / organization_members', 'org identity + membership with org_role and approval limits'),
    ('bulk_payout_batches / _items', 'batch status (draft to completed), items with per-item transaction and failure reason'),
    ('api_keys / webhook_endpoints', 'hashed keys with keyPrefix and scopes; webhook URLs with secret and event list'),
    ('compliance_alerts / card_disputes', 'AML alerts (rule, severity, status) and card disputes with resolution notes'),
    ('audit_logs / support_tickets (+_messages)', 'actor-action-resource audit trail; ticket threads with staff flags'),
], 'Table 13 - Principal database tables')
story.extend(h2_block('4.2 Design Notes'))
story.append(Paragraph('• <b>Money is never stored as float</b> - all amounts are bigint minor units.', bullet))
story.append(Paragraph('• <b>Double-entry invariant</b> - each transaction produces balanced debit/credit legs; '
                       'conversions are balanced per currency via system wallets.', bullet))
story.append(Paragraph('• <b>Idempotency at the schema level</b> - a unique constraint on transactions.idempotencyKey '
                       'backs the Redis interceptor.', bullet))
story.append(Paragraph('• <b>Soft lifecycle</b> - wallets, cards and accounts are closed/frozen, not deleted; user '
                       'closure feeds the NDPR retention purge.', bullet))

# ================= 5. Mobile App =================
story.extend(h1_block('5. Mobile Application'))
story.append(Paragraph(
    'The customer app is an Expo 54 / React Native 0.81 application with file-based routing '
    '(<font name="DejaVuSans">app/</font> directory, typed routes, bundle id '
    '<font name="DejaVuSans">com.novapay.app</font>). State is provided by AuthContext and WalletsContext; API '
    'clients live in <font name="DejaVuSans">src/lib/</font> with sessions persisted in Expo SecureStore. The '
    'local PIN is salted-SHA-256 hashed and stored in SecureStore, with optional biometric unlock via '
    '<font name="DejaVuSans">expo-local-authentication</font>.', body))
ep_table([
    ('Onboarding (auth group)', 'welcome carousel, phone entry (E.164), OTP verification, PIN setup/unlock, KYC document flow'),
    ('Home (tabs/index)', 'balance hero, currency strip, quick actions (Add, Convert, Pay, Receive), recent activity'),
    ('Send / Beneficiaries', 'send-money, add-beneficiary; payouts gated by KYC tier'),
    ('Fund / Convert', 'add-money keypad flow; conversion with locked FX quote and countdown'),
    ('Cards', 'cards list, create-card, card-details (freeze/unfreeze/close, simulated purchase)'),
    ('Receive', 'USD/EUR virtual account details and simulated inbound credit'),
    ('Activity / Bills', 'filterable transaction history with day groups; bills and airtime purchase'),
    ('Stablecoins', 'USDC/USDT deposit and convert'),
    ('Business', 'business and business-org screens: orgs, members, funding, bulk payouts and approvals'),
    ('Profile & Help', 'edit-profile, change-pin, help centre and help-ticket creation'),
], 'Table 14 - Mobile screens by feature area')

# ================= 6. Admin Console =================
story.extend(h1_block('6. Admin Console'))
story.append(Paragraph(
    'The operations console (React 19 + Vite + React Router 7) authenticates with the same phone-OTP flow '
    'against platform roles; admin phones are seeded via <font name="DejaVuSans">ADMIN_SEED_PHONES</font> '
    '(default seed: +2348000000001). In development, <font name="DejaVuSans">/v1</font> requests are proxied to '
    'the API on port 3000 and the session token is held in localStorage.', body))
ep_table([
    ('LoginPage', 'Phone + OTP sign-in for staff roles'),
    ('CustomersPage / CustomerDetailPage', 'Search customers, view wallets, suspend/close accounts, see open tickets'),
    ('KycPage', 'Manual KYC approve/reject, moving users to tier_1 or tier_2'),
    ('TransactionsPage / TransactionDetailPage', 'Platform-wide search and filters; per-transaction ledger legs'),
    ('TicketsPage / TicketDetailPage', 'Support queue with full message thread and replies'),
    ('AlertsPage', 'AML alert review: dismiss, or confirm and act'),
    ('DisputesPage', 'Resolve card disputes; a "won" resolution triggers a ledger reversal'),
    ('ReconPage', 'Run a reconciliation job and view daily Flutterwave-vs-ledger reports'),
], 'Table 15 - Admin console pages')

# ================= 7. Money Movement & Pricing =================
story.extend(h1_block('7. Money Movement, FX and Pricing'))
story.extend(h2_block('7.1 Double-Entry Ledger'))
story.append(Paragraph(
    'All balances derive from ledger entries, never from mutable balance columns. Funding credits a user wallet '
    'and debits a system clearing wallet; payouts do the reverse; conversion legs are balanced per currency '
    'through per-currency system wallets. Every entry records the running balanceAfter for auditability.', body))
story.extend(h2_block('7.2 Fee Engine'))
story.append(Paragraph(
    'Fees are configured per transaction type as basis points plus a flat component, clamped by min/max, e.g. '
    '<font name="DejaVuSans">FEE_FUND_BPS=50</font> and <font name="DejaVuSans">FEE_PAYOUT_BPS=100</font> plus a '
    '50-kobo flat. Fund fees are deducted from the credit; payout fees are added to the debit. Collected fees '
    'post to the dedicated <font name="DejaVuSans">fees</font> system wallet, and customers can pre-quote via '
    '<font name="DejaVuSans">GET /v1/fees/quote</font>.', body))
story.extend(h2_block('7.3 FX Pricing'))
story.append(Paragraph(
    'Mid-market rates come from a static table (e.g. <font name="DejaVuSans">FX_USD_NGN_MID=1600</font>), an HTTP '
    'provider (frankfurter) or auto mode, cached in Redis. The customer rate applies a disclosed margin '
    '(<font name="DejaVuSans">FX_MARGIN_BPS=150</font> default). Quotes are locked for 60 seconds by default and '
    'booked atomically.', body))

# ================= 8. Compliance & Security =================
story.extend(h1_block('8. Compliance, Risk and Security'))
story.extend(h2_block('8.1 KYC Tiers and Limits'))
story.append(Paragraph(
    'Users carry a KYC tier (tier_0/1/2) enforced on payouts and wallet balances - for example tier_0 cannot pay '
    'out and its wallet is capped at NGN 50,000, while higher tiers unlock single/daily/monthly payout limits. '
    'KYC can be auto-approved in development (<font name="DejaVuSans">KYC_AUTO_APPROVE</font>) and is manually '
    'reviewed in the admin console otherwise.', body))
story.extend(h2_block('8.2 AML, Sanctions and Velocity'))
story.append(Paragraph(
    'Payouts and card authorisations pass sanctions screening (mock or HTTP provider) and velocity checks backed '
    'by Redis counters. Large-amount activity raises compliance alerts for admin review. Won disputes trigger '
    'automatic ledger reversals. A retention service purges data for closed users in line with NDPR.', body))
story.extend(h2_block('8.3 Application Security'))
story.append(Paragraph('• OTPs hashed with a pepper, timing-safe compared, with lockout; log-mode SMS disabled in production.', bullet))
story.append(Paragraph('• JWT refresh rotation with server-side jti registry; full session revocation supported.', bullet))
story.append(Paragraph('• API keys stored only as hashes with a visible prefix; scopes attached at resolution time.', bullet))
story.append(Paragraph('• Step-up authentication for payouts above a configurable threshold.', bullet))
story.append(Paragraph('• Global throttling, helmet headers, structured logging with auth-header redaction, and Zod-validated environment config.', bullet))

# ================= 9. Configuration =================
story.extend(h1_block('9. Configuration Reference'))
story.append(Paragraph(
    'Configuration is loaded from environment variables and validated at boot with Zod '
    '(<font name="DejaVuSans">config/env.validation.ts</font>). The template is '
    '<font name="DejaVuSans">.env.example</font>. Key groups:', body))
ep_table([
    ('Database', 'DATABASE_URL (pooler), DATABASE_URL_DIRECT (migrations)'),
    ('Redis', 'REDIS_URL'),
    ('Auth', 'JWT secrets and TTLs (15m access / 30d refresh), OTP_PEPPER, OTP_MAX_ATTEMPTS, OTP_LOCKOUT_SECONDS, AUTH_STEPUP_PAYOUT_MINOR'),
    ('OTP delivery', 'SMS_OTP_MODE=log|http|twilio|infobip, OTP_DEV_FIXED_CODE (dev only)'),
    ('KYC', 'KYC_AUTO_APPROVE, KYC_PROVIDER'),
    ('Payments', 'PAYMENT_RAIL=auto|mock|flutterwave, FLUTTERWAVE keys'),
    ('FX', 'FX_RATE_MODE, FX_USD_NGN_MID, FX_USD_EUR_MID, FX_MARGIN_BPS, FX_QUOTE_TTL_SECONDS, FX_HTTP_URL'),
    ('Fees', 'FEE_FUND_BPS, FEE_PAYOUT_BPS (+flat), per-type schedules'),
    ('Idempotency', 'IDEMPOTENCY_TTL_SECONDS (default 86400)'),
    ('Partners', 'CARD_ISSUER, BAAS_PROVIDER, MOMO_AGGREGATOR, SANCTIONS_PROVIDER'),
    ('Ops', 'THROTTLE settings, SWAGGER_ENABLED, ADMIN_SEED_PHONES'),
], 'Table 16 - Environment configuration groups')

# ================= 10. Testing & CI =================
story.extend(h1_block('10. Testing and CI'))
story.append(Paragraph(
    'Unit tests (Jest) cover the financially critical logic: OTP hashing and TTL parsing, fee math, FX '
    'conversion and rounding, ledger balance math, pagination, the error envelope, environment validation, '
    'compliance rules and an auth-to-payment integration spec. End-to-end specs run against a live API: '
    'bootstrap/health checks and a full OTP login to funding to payout journey. CI (GitHub Actions) executes '
    'lint, unit tests with a Redis service container, and a TypeScript build on Node 22 for every push and PR '
    'to main/develop. The mobile and admin apps currently have no automated tests.', body))

# ================= 11. Deployment =================
story.extend(h1_block('11. Deployment and Operations'))
story.append(Paragraph('• <b>Local stack</b>: <font name="DejaVuSans">docker compose up -d</font> starts Redis; '
                       'add <font name="DejaVuSans">--profile local-db</font> for a local PostgreSQL instead of Supabase.', bullet))
story.append(Paragraph('• <b>API image</b>: multi-stage node:22-alpine build; run with '
                       '<font name="DejaVuSans">node dist/main.js</font> as a non-root user on port 3000.', bullet))
story.append(Paragraph('• <b>Migrations</b>: Drizzle Kit against the direct database URL '
                       '(<font name="DejaVuSans">drizzle-kit migrate/generate/push/studio</font>).', bullet))
story.append(Paragraph('• <b>Health</b>: <font name="DejaVuSans">/health</font> (DB + Redis) and '
                       '<font name="DejaVuSans">/health/live</font> for load-balancer probes.', bullet))
story.append(Paragraph('• <b>API docs</b>: Swagger UI at <font name="DejaVuSans">/docs</font> when enabled.', bullet))

# ================= 12. Roadmap =================
story.extend(h1_block('12. Delivery Roadmap and Status'))
ep_table([
    ('Phase 0 - Foundations', 'NestJS scaffold, config validation, Supabase/Drizzle, Redis, health, logging, Docker, CI', 'Done (engineering)'),
    ('Phase 1 - MVP backend', 'Phone-OTP auth, KYC auto-approve, NGN wallet, double-entry ledger, mock rail fund/payout', 'Done'),
    ('Phase 2 - FX + cards', 'Transparent FX quotes, NGN/USD conversion, virtual USD card issuer', 'Done'),
    ('Phase 3 - Receive + bills', 'USD/EUR virtual accounts, inbound rails, MoMo beneficiaries, bills/airtime, EUR wallet', 'Done'),
    ('Phase 4 - Business + API', 'Organisations, approval-limited bulk payouts, stablecoins, physical cards, API keys + webhooks', 'Done'),
    ('Phase 5 - Hardening', 'Error envelope, pagination, idempotency, throttling, Swagger, tests in CI', 'Done'),
    ('Phase 6 - Pricing', 'Fee engine, fees system wallet, live FX mids with margin disclosure, reconciliation', 'Done'),
    ('Phase 7 - Compliance', 'KYC tier limits, sanctions, AML alerts, velocity controls, disputes, NDPR retention', 'Done'),
    ('Phase 8 - Auth hardening', 'Hashed OTPs, lockout, refresh rotation, pluggable SMS, step-up, hashed mobile PIN', 'Done'),
    ('F0-F7 - Mobile frontend', 'Design system, onboarding, wallets/funding, convert/send, cards, bills/receive, stablecoins, business', 'Done'),
    ('Admin console', 'Customers, KYC review, transactions, support, AML alerts, disputes, reconciliation', 'Done'),
], 'Table 17 - Phase status summary')
story.append(Paragraph(
    'Open items noted in the phase documents: selecting production partners (KYC, BaaS, card issuer, MoMo '
    'aggregator, sanctions) and regulatory licensing for Supabase-hosted data; all integrations currently run '
    'behind mock providers switchable via configuration.', body))

# ---- Build ----
doc = TocDocTemplate(
    '/home/ola-oladimeji/Desktop/NovaPay/docs/novapay_body.pdf', pagesize=A4,
    leftMargin=MARGIN, rightMargin=MARGIN, topMargin=MARGIN + 6, bottomMargin=MARGIN,
    title='NovaPay Technical Documentation', author='Z.ai', creator='Z.ai',
    subject='Full technical documentation of the NovaPay cross-border banking platform')

def on_page(canvas, doc_):
    canvas.saveState()
    canvas.setFont('Times New Roman', 7.5)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(MARGIN, PAGE_H - 30, 'NovaPay Technical Documentation')
    canvas.setStrokeColor(HEADER_FILL); canvas.setLineWidth(1.2)
    canvas.line(MARGIN, PAGE_H - 36, PAGE_W - MARGIN, PAGE_H - 36)
    canvas.setStrokeColor(BORDER); canvas.setLineWidth(0.5)
    canvas.line(MARGIN, MARGIN - 12, PAGE_W - MARGIN, MARGIN - 12)
    canvas.drawString(MARGIN, MARGIN - 24, 'NovaPay')
    canvas.drawRightString(PAGE_W - MARGIN, MARGIN - 24, 'Page %d' % doc_.page)
    canvas.restoreState()

doc.multiBuild(story, onFirstPage=on_page, onLaterPages=on_page)
print('body built')
